---
- name: Update and upgrade RHEL server
  hosts: all
  gather_facts: true
  become: true
  vars:
    release_upgrade: true
    release_version: "8.8"
  tasks:
    - name: Set RHEL release version
      community.general.rhsm_release:
        release: "{{ release_version }}"
      when: release_upgrade | bool is true and release_version is defined
      register: release_result

    - name: Perform yum upgrade
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Check if reboot is required
      ansible.builtin.shell: |
        dnf needs-restarting -r
      register: reboot_check
      changed_when: false
      ignore_errors: true

    - name: Reboot server if required
      ansible.builtin.reboot:
        reboot_timeout: 600
        msg: "Ansible is rebooting to apply updates"
      when: reboot_check.stdout | regex_search('Reboot is required')

    - name: Force a facts update
      ansible.builtin.shell: |
        subscription-manager facts --update
      changed_when: false
      ignore_errors: true
      when: release_result.changed
...
