---
- name: Update and upgrade RHEL server
  hosts: all
  gather_facts: false
  become: true
  vars:
    release_upgrade: true
    release_version: "8.6"
  tasks:
    - name: Set RHSM release version
      community.general.rhsm_release:
        release: "{{ release_upgrade }}"
      when: release_upgrade is true and release_version is defined

    - name: Perform yum upgrade
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Check if reboot is required
      ansible.builtin.command: dnf needs-restarting -r
      register: reboot_check
      changed_when: false
      ignore_errors: true

    - name: Reboot server if required
      ansible.builtin.reboot:
        reboot_timeout: 600
        msg: "Ansible is rebooting to apply updates"
      when: reboot_check.stdout | regex_search('Reboot is required')
...
